# Generated by Django 3.2.11 on 2022-01-22 19:37

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_related_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='related_groups',
        ),
        migrations.AddField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='test_django@gmail.com', max_length=64),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
