# Generated by Django 3.2.11 on 2022-02-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_auto_20220210_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.PositiveIntegerField(choices=[(1, 'Teacher'), (2, 'MENTOR')], default=1),
        ),
    ]
