# Generated by Django 3.2.11 on 2022-02-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.AddField(
            model_name='teacher',
            name='level',
            field=models.PositiveIntegerField(choices=[(1, 'Teacher'), (2, 'MENTOR')], default=1),
        ),
    ]
