# Generated by Django 3.2.11 on 2022-02-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_auto_20220219_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='level',
        ),
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.PositiveIntegerField(choices=[(1, 'Teacher'), (2, 'Mentor')], default=1),
        ),
    ]
